
version: '3.8'

services:
 web:
  build:
   dockerfile: ./src/Dockerfile
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/code
  env_file:
  - ./.env.dev
  command: python ./src/manage.py run -h 0.0.0.0 -p 5000

#  mysqldb:
#   image: mysql
#   ports:
#   - 3306:3306
#   environment:
#   - MYSQL_ROOT_PASSWORD=p@ssw0rd1
#   volumes:
#   - mysql:/var/lib/mysql
#   - mysql_config:/etc/mysql

# volumes:
#   mysql:
#   mysql_config:
